### ISSUE TITLE
Ability for bot to give Ansible related responses

### ISSUE THREAD

**Issue by AmaterasuSecurity** [CyberSentinels/discord-cyber-scenario-bot#27]
Bot is unable to give Ansible related answers when prompted in Discord (Sorry Simeon, ddn't know which repo so i chose this one).

**Comment by simeononsecurity** [comment]
the correct one would be here https://github.com/CyberSentinels/discord-typecast-gpt-chatbot/issues
I've gone ahead and addressed it with the following change https://github.com/CyberSentinels/discord-typecast-gpt-chatbot/commit/33ec2125decc298369df503c00b407892a5b1090
