### ISSUE TITLE
CodeGrepper functionally

### ISSUE THREAD

**Issue by dr0pp3dpack3ts** [CyberSentinels/discord-cyber-scenario-bot#9]
Be able to grep code with the bot.

**Comment by simeononsecurity** [comment]
This would be difficult. You'd have to supply the source code, and specify the type of code. 
Supporting this and also grep could be pretty dangerous. I'm open to the idea, but it would be a lot of work. Would need to see some traction and buy in on this idea before even starting implementation.

**Comment by simeononsecurity** [comment]
To an extent this is covered with https://github.com/CyberSentinels/discord-typecast-gpt-chatbot
